---
apiVersion: v2
name: senzing-console
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: senzing-console
    version: 2.3.1
    repository: https://hub.senzing.com/charts
