---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ullswater-appset
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: https://github.com/bolaogun/ullswater-appset
      revision: develop
      directories:
      - path: preapps/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: '\{\{$$appNamespace\}\}'
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      # finalizers:
      # - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: https://github.com/bolaogun/ullswater-appset
        targetRevision: develop
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
