---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ullswater-gitops-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bolaogun/ullswater-appset
    targetRevision: develop
    path: gitops
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ullswater-gitops-application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
