---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: senzing-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
        - chartName: senzing-console
          targetRevision: 2.3.1
          helmValues: ""
        - chartName: senzing-debug
          targetRevision: 1.3.0
          helmValues: ""
  template:
    metadata:
      name: '{{ chartName }}'
      namespace: '\{\{$$appNamespace\}\}'
    spec:
      project: default
      source:
        chart:  '{{ chartName }}'
        targetRevision: '{{ targetRevision }}'
        repoURL: https://hub.senzing.com/charts
        helm:
          values: '{{ helmValues }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: senzing
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
        - Validate=false
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true