---
apiVersion: v2
name: redisinsight
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: redisinsight
    version: 0.1.0
    repository: https://spy86.github.io/redisinsight
