{{- if .Values.senzingStack.enabled -}}
{{- $nmSpc := .Values.senzingStack.namespace -}}
{{- $rpUrl := .Values.senzingStack.repoURL -}}
{{- range .Values.senzingStack.components }}
{{- if and .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .chartName | quote }}
  namespace: argocd
spec:
  project: default
  source:
    chart: {{ .chartName | quote }}
    targetRevision: {{ .targetRevision }}
    repoURL: {{ $rpUrl | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $nmSpc | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
{{- end }}
{{- end }}
{{- end }}
