---
apiVersion: v2
name: senzing-swagger-ui
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: senzing-swagger-ui
    version: 2.3.0
    repository: https://hub.senzing.com/charts
