---
apiVersion: v2
name: strimzi-kafka-operator
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: strimzi-kafka-operator
    version: 0.32.0
    repository: https://strimzi.io/charts/
