---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ullswater-senzing-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  source:
    path: apps/senzing-stack/
    repoURL: 'https://github.com/bolaogun/ullswater-appset'
    targetRevision: develop
    directory:
      recurse: true
  destination:
    namespace: senzing
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=false
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true